spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study_room?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: yuhan20020920
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-locations: classpath:mybatis/mybatis-config.xml

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
